// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/oa-meeting/pkg/aliyun"
	"github.com/oa-meeting/pkg/app"
	"github.com/oa-meeting/pkg/cache"
	"github.com/oa-meeting/pkg/db"
	"github.com/oa-meeting/pkg/logger"
	"github.com/oa-meeting/pkg/snowf"
	"github.com/oa-meeting/pkg/tracing"
)

import (
	_ "dubbo.apache.org/dubbo-go/v3/filter/tps/strategy"
	_ "dubbo.apache.org/dubbo-go/v3/imports"
	_ "github.com/oa-meeting/internal/handler"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	zapLogger := logger.ZapInit()
	client := cache.NewRedis()
	jaegerProvider := tracing.NewTracing()
	gormDB := db.NewMeeting()
	node := snowf.NewSf()
	clientClient := aliyun.NewRtcClient()
	appApp := NewApp(zapLogger, client, jaegerProvider, gormDB, node, clientClient)
	return appApp, nil
}
