system:
  mode: dev #正式 prod #测试 test #开发 dev
mealOrder:
  host: 127.0.0.1
  port: 3306
  user: dyb
  password: rootdyb
  db_name: "oa-meeting"
redis:
  db: 1
  addr: 127.0.0.1:6379
  password: "7532T6R"
zapLog:
  level: "info"
  filename: "logs/oa-meeting.log"
  max_size: 5
  max_age: 30
  max_backups: 30
snowflake:
  node_num: 4
  start_time: "2023-05-31"
jaeger:
  addr: "127.0.0.1:6831"
  open: false
rabbitmq:
  user: "myuser"
  password: "mypass"
  host: "localhost"
  port: 5672
  vhost: "oa"